name: checkov-scan
run-name: ${{ github.workflow }}
on:
  workflow_dispatch:

jobs:
  scan-and-publish:
    name: Scan bicep and publish results
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    steps:
      - name: Harden Runner
        if: inputs.enable_harder_runner == 'true'
        uses: step-security/harden-runner@v2.0.0
        with:
          disable-sudo: true
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      # When testing the bicep templates directly, the modules are not included.
      - name: Bicep build
        uses: Azure/bicep-build-action@v1.0.0
        with:
          bicepFilePath: bicep/azure.deploy.bicep
          outputFilePath: bicep/azure.deploy.json

      - name: Scan with Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          file: bicep/azure.deploy.json
          framework: arm
          soft_fail: false
          output_format: sarif # junitxml
          output_file_path: results.sarif

      - name: Write results to file
        if: success() || failure()
        run: |
          echo "$CHECKOV_RESULTS" > results2.sarif

      - name: Upload results as artifact
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: scan-results
          path: |
            results.sarif
            results2.sarif
          retention-days: 30

      # - name: Publish scan results
      #   uses: mikepenz/action-junit-report@v3
      #   if: always()
      #   with:
      #     check_name: Checkov Scan Results
      #     report_paths: results.xml
      #     detailed_summary: true

      - name: Upload SARIF file
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
          category: psrule

      - name: Upload SARIF file
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results2.sarif
          # category: psrule
