name: destroy-infra

run-name: ${{ github.workflow }}

on:
  workflow_dispatch:
    inputs:
      rg_name:
        description: "Define resource group name"
        required: true
        type: string

env:
  SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  RG_NAME: ${{ inputs.rg_name }}

jobs:
  approve:
    name: Approve infrastructure teardown
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.0.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443

      - name: Checkout
        uses: actions/checkout@v3

      - name: Manual Workflow Approval
        uses: trstringer/manual-approval@v1.6.0
        with:
          approvers: christosgalano
          minimum-approvals: 1
          secret: ${{ github.TOKEN }}

  destroy:
    name: Destroy Infrastructure
    needs: approve
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        shell: bash
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.0.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            azure.microsoft.com:443
            dc.services.visualstudio.com:443
            github.com:443
            login.microsoftonline.com:443
            management.azure.com:443
            *.mcr.microsoft.com:443
            mcr.microsoft.com:443
            raw.githubusercontent.com:443

      - name: Checkout
        uses: actions/checkout@v3

      - name: Azure Login
        uses: Azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Delete the resource group and all of its resources
        uses: Azure/cli@v1
        with:
          inlineScript: az group show -n $RG_NAME
          # inlineScript: az group delete -n $RG_NAME -y
      - name: Test curl
        run: |
          curl www.google.com
