name: psrule-scan
run-name: ${{ github.workflow }}
on:
  workflow_dispatch:
    inputs:
      code_scanning_enabled:
        description: "Specify whether to integrate with code scanning"
        required: true
        type: boolean

jobs:
  call-psrule-scan-workflow:
    permissions:
      security-events: write
      actions: read
      checks: write
      contents: read
    uses: christosgalano/Workflow-Templates/.github/workflows/psrule_scan.yaml@main
    with:
      template_dir: bicep
      template_prefix: azure.deploy
      code_scanning_enabled: ${{ inputs.code_scanning_enabled }}
      enable_harder_runner: false
