name: scan-iac

run-name: ${{ github.workflow }}

on:
  workflow_dispatch:

jobs:
  scan-and-publish:
    name: Scan IaC
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      # When testing the bicep templates directly, the modules are not included.
      - name: Bicep Build
        uses: Azure/bicep-build-action@v1.0.0
        with:
          bicepFilePath: bicep/main.bicep
          outputFilePath: bicep/main.json

      - name: Scan with Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          file: bicep/main.json
          framework: arm
          soft_fail: false
          output_format: junitxml

      - name: Write results
        working-directory: reports
        if: always()
        run: |
          echo "$CHECKOV_RESULTS" > results.xml

      - name: Upload results as artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: scan-report
          path: reports/results.xml
          retention-days: 5

      - name: Publish Scan Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          check_name: Checkov Scan Report
          report_paths: "reports/results.xml"
          detailed_summary: true
